name: Test

on:
  push:
    branches-ignore:
      - main
      - alpha
      - beta
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - run: npm run lint
